### ISSUE TITLE
I would like more payment options

### ISSUE THREAD

**Issue by carloss66** [jameskoster/woocommerce-accepted-payment-methods#1]
I would like to see Discover, Money Order, and Cash as payment options.  I get cash payments on local order pickups.

**Comment by jameskoster** [comment]
Will add more payment options when I have time. Feel free to fork and add them yourself :-)

**Comment by Ramoonus** [comment]
@jameskoster will fork, might commit

**Comment by jameskoster** [comment]
@Ramoonus go ahead please!

**Comment by Ramoonus** [comment]
@jameskoster I don`t have access to all plugins, like you do :-P

**Comment by jameskoster** [comment]
huh? :-)

**Comment by Ramoonus** [comment]
i don`t have access to all the payment plugins, like you do

**Comment by jameskoster** [comment]
What does that have to do with adding payment options to this plugin? :-P They're just logos...

**Comment by Ramoonus** [comment]
true but i mean the detection of active plugins

**Comment by jameskoster** [comment]
Ah right, it's not that clever ;-) Just requires users to select which methods they accept, no detection.

**Comment by jameskoster** [comment]
I added discover in 0.3.
